// Tests for the automated "is there a newer version" check (see #1166, Phase 2).
// The registry subprocesses (npm view / uv pip compile) are not exercised here —
// the pure parsers are unit-tested, and checkPackageUpdate takes an injectable
// query seam so orchestration, caching and comparison run without network.

import {
  parseNpmViewVersion,
  parseUvCompileVersion,
  isNewerVersion,
  checkPackageUpdate,
  clearPackageUpdateCache,
} from './packageUpdate.js';

describe('parseNpmViewVersion', () => {
  it('returns the version line', () => {
    expect(parseNpmViewVersion('1.6.0\n')).toBe('1.6.0');
  });

  it('trims surrounding whitespace and blank lines', () => {
    expect(parseNpmViewVersion('  \n  1.6.0  \n\n')).toBe('1.6.0');
  });

  it('returns undefined for empty output', () => {
    expect(parseNpmViewVersion('\n  \n')).toBeUndefined();
  });
});

describe('parseUvCompileVersion', () => {
  const compileOutput = (targetLine: string): string =>
    `# This file was autogenerated by uv via the following command:\n${targetLine}\n    # via -r /tmp/req.txt\n`;

  it('parses the target package line', () => {
    expect(parseUvCompileVersion(compileOutput('cowsay==6.1'), 'cowsay')).toBe('6.1');
  });

  it('ignores transitive dependency lines', () => {
    const out = 'anyio==4.15.1\n    # via pydantic\ncowsay==6.1\n    # via -r /tmp/req.txt\n';
    expect(parseUvCompileVersion(out, 'cowsay')).toBe('6.1');
  });

  it('matches a dashed package name exactly', () => {
    expect(
      parseUvCompileVersion(compileOutput('mcp-server-fetch==2026.8.18'), 'mcp-server-fetch'),
    ).toBe('2026.8.18');
  });

  it('returns undefined when the package is absent', () => {
    expect(parseUvCompileVersion('anyio==4.15.1\n    # via pydantic\n', 'cowsay')).toBeUndefined();
  });
});

describe('isNewerVersion', () => {
  it('is true when latest is newer', () => {
    expect(isNewerVersion('2.0.0', '1.6.0')).toBe(true);
  });

  it('is false when versions match', () => {
    expect(isNewerVersion('1.6.0', '1.6.0')).toBe(false);
  });

  it('is false when latest is older', () => {
    expect(isNewerVersion('1.5.0', '1.6.0')).toBe(false);
  });

  it('compares multi-digit segments numerically', () => {
    expect(isNewerVersion('10.0.0', '9.9.9')).toBe(true);
  });

  it('treats missing trailing segments as zero', () => {
    expect(isNewerVersion('1.6.0', '1.6')).toBe(false);
  });

  it('handles a leading v prefix', () => {
    expect(isNewerVersion('v2.0.0', '1.9.0')).toBe(true);
  });

  it('falls back to string order on non-numeric segments', () => {
    expect(isNewerVersion('1.0.beta', '1.0.alpha')).toBe(true);
  });

  it('treats digit-prefixed prerelease suffixes as their numeric prefix', () => {
    // '0-rc' parses as 0, so both sides compare as 1.0.0.1 — not an update.
    expect(isNewerVersion('1.0.0-rc.1', '1.0.0-alpha.1')).toBe(false);
  });
});

describe('checkPackageUpdate', () => {
  const baseOpts = { cacheTtlMs: 60_000 };

  beforeEach(() => {
    clearPackageUpdateCache();
  });

  it('reports an update for npx when the registry has a newer version', async () => {
    const queryLatest = jest.fn(async () => '2.0.0');
    const result = await checkPackageUpdate('npx', ['-y', 'cowsay'], '1.6.0', {
      ...baseOpts,
      queryLatest,
    });

    expect(result).toEqual({ latestVersion: '2.0.0', updateAvailable: true });
    expect(queryLatest).toHaveBeenCalledWith('npx', 'cowsay', expect.anything());
  });

  it('reports no update when the registry version matches', async () => {
    const queryLatest = jest.fn(async () => '1.6.0');
    const result = await checkPackageUpdate('uvx', ['cowsay'], '1.6.0', {
      ...baseOpts,
      queryLatest,
    });

    expect(result).toEqual({ latestVersion: '1.6.0', updateAvailable: false });
  });

  it('resolves the package named by a uvx --from option', async () => {
    const queryLatest = jest.fn(async () => '0.2.0');
    const result = await checkPackageUpdate(
      'uvx',
      ['--from', 'mcp-server-fetch', 'mcp-server-fetch', '--port', '9000'],
      '0.1.0',
      { ...baseOpts, queryLatest },
    );

    expect(result?.updateAvailable).toBe(true);
    expect(queryLatest).toHaveBeenCalledWith('uvx', 'mcp-server-fetch', expect.anything());
  });

  it('does not query when the package cannot be identified', async () => {
    const queryLatest = jest.fn(async () => '2.0.0');
    const result = await checkPackageUpdate('npx', ['-c', 'echo hi'], '1.0.0', {
      ...baseOpts,
      queryLatest,
    });

    expect(result).toBeUndefined();
    expect(queryLatest).not.toHaveBeenCalled();
  });

  it('returns undefined for unsupported commands', async () => {
    const queryLatest = jest.fn(async () => '2.0.0');
    const result = await checkPackageUpdate('node', ['server.js'], '1.0.0', {
      ...baseOpts,
      queryLatest,
    });

    expect(result).toBeUndefined();
    expect(queryLatest).not.toHaveBeenCalled();
  });

  it('returns undefined when the registry query fails', async () => {
    const queryLatest = jest.fn(async () => undefined);
    const result = await checkPackageUpdate('npx', ['-y', 'cowsay'], '1.6.0', {
      ...baseOpts,
      queryLatest,
    });

    expect(result).toBeUndefined();
  });

  it('caches the latest version within the TTL', async () => {
    const queryLatest = jest.fn(async () => '2.0.0');
    const opts = { ...baseOpts, queryLatest };

    await checkPackageUpdate('npx', ['-y', 'cowsay'], '1.0.0', opts);
    await checkPackageUpdate('npx', ['-y', 'cowsay'], '1.0.0', opts);

    expect(queryLatest).toHaveBeenCalledTimes(1);
  });

  it('re-queries after the TTL expires', async () => {
    const queryLatest = jest.fn(async () => '2.0.0');
    const opts = { cacheTtlMs: 1, queryLatest };

    await checkPackageUpdate('npx', ['-y', 'cowsay'], '1.0.0', opts);
    await new Promise((resolve) => setTimeout(resolve, 5));
    await checkPackageUpdate('npx', ['-y', 'cowsay'], '1.0.0', opts);

    expect(queryLatest).toHaveBeenCalledTimes(2);
  });
});
